version: "2.4"
services:
  mockServer:
    image: mockserver/mockserver:mockserver-snapshot
    ports:
      - 8080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/init.json
    volumes:
      - type: bind
        source: .
        target: /config
